# Generated by Django 4.2.11 on 2024-07-30 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_background', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('service_background', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('gallery_background', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('blog_background', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('about_background', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('contact_background', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='_ no name _', max_length=255)),
                ('tagline', models.CharField(default='_ no tagline _', max_length=255)),
                ('description', models.CharField(default='_ no description _', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo')),
                ('dashboard_logo', models.ImageField(blank=True, null=True, upload_to='site/logo')),
                ('favico', models.ImageField(blank=True, null=True, upload_to='site/favico')),
                ('about_title', models.CharField(max_length=200)),
                ('about_short_discription', tinymce.models.HTMLField(blank=True, null=True)),
                ('about_image_1', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('about_image_2', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('about_image_3', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('service_title', models.CharField(blank=True, max_length=200, null=True)),
                ('event_title', models.CharField(blank=True, max_length=200, null=True)),
                ('gallery_title', models.CharField(blank=True, max_length=200, null=True)),
                ('blog_title', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(default='_ no address provided _', max_length=1000)),
                ('phone', models.CharField(default='+000000000000', max_length=15)),
                ('email', models.EmailField(default='noname@domain.com', max_length=255)),
                ('privacy_content', tinymce.models.HTMLField(default='*')),
                ('terms_content', tinymce.models.HTMLField(default='*')),
                ('disclaimer_content', tinymce.models.HTMLField(default='*')),
                ('contact_content', tinymce.models.HTMLField(default='*')),
                ('service_content', tinymce.models.HTMLField(default='*')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Site',
            },
        ),
        migrations.CreateModel(
            name='SitePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/partner/logo')),
            ],
        ),
        migrations.CreateModel(
            name='SiteTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='site/partner/logo')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_1', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_2', models.CharField(blank=True, max_length=30, null=True)),
                ('tag_3', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(upload_to='slider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Services Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.gallerycategory')),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.gallerycategory')),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.eventcategory')),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255, verbose_name='host name')),
                ('thumbnail_image', models.ImageField(upload_to='books/images/posts')),
                ('slug', models.SlugField(unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('country', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=100)),
                ('exact_destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='publish', max_length=15)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_category', to='website.eventcategory')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.blogcategory')),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='books/images/posts')),
                ('slug', models.SlugField(unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('read_time', models.PositiveIntegerField(default=0, help_text='read time in minutes')),
                ('visits', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='publish', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_category', to='website.blogcategory')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
